[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "ProLUG Security Course"

[output.html]
site-url = "/psc/"
default-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/ProfessionalLinuxUsersGroup/psc"
edit-url-template = "https://github.com/ProfessionalLinuxUsersGroup/psc/issues"
git-repository-icon = "fa-github"
